tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaaca7lntmtszny3mgfhmzb5jb5oi6xucnrb7z6emorxdzheos4m4pa"
compartment_id   = "ocid1.tenancy.oc1..aaaaaaaaca7lntmtszny3mgfhmzb5jb5oi6xucnrb7z6emorxdzheos4m4pa"
region           = "us-ashburn-1"
internet_gateway_enabled = "true"
internet_gateway_display_name = "Ashburn Internet Gateway"